/* CORINTHIANS NOVA ERA — MATCH CORE */
(function(){
"use strict";
const M={
 init(G){const s=G.state;s.matchEngine=s.matchEngine||{};return s;},
 players(G){const s=G.state,ids=Object.values(s.lineup||{});return (s.squad||[]).filter(p=>ids.includes(p.id)&&!p.injured&&!p.suspended);},
 rating(G,team){if(team==="Corinthians")return window.UnifiedCareerCore?UnifiedCareerCore.teamStrength(G):76;const r={Flamengo:83,Palmeiras:83,Atletico-MG:81,"Atlético-MG":81,Internacional:79,"São Paulo":79,Fluminense:78,Botafogo:78,Grêmio:77,Corinthians:80,Bahia:76,Cruzeiro:75,Bragantino:74,Vasco:73,Santos:72,Vitória:71,Ceará:70,Sport:69,Mirassol:68,Chapecoense:66,Remo:65};return r[team]||73;},
 start(G,f){if(!f||G.state.matchEngine?.active)return false;const h=f.home||"Corinthians",a=f.away||f.opponent||"Adversário";G.state.matchEngine={active:true,fixtureId:f.id||Date.now(),minute:0,home:h,away:a,events:[{minute:0,type:"system",text:"Apito inicial."}],cards:{home:[],away:[]},substitutions:[],halftime:false,stats:{home:{shots:0,shotsOnTarget:0,possession:50,xg:0,cards:0},away:{shots:0,shotsOnTarget:0,possession:50,xg:0,cards:0}},score:{home:0,away:0},playerRatings:{}};this.players(G).forEach(p=>G.state.matchEngine.playerRatings[p.id]=6.5);f.status="live";G.addNews("🏟️ Matchday",h+" x "+a+" começou.","JOGO");return true;},
 minute(G){const s=G.state,m=s.matchEngine;const hs=this.rating(G,m.home),as=this.rating(G,m.away),home=hs+5+(s.fanMood-50)*.12,away=as,total=home+away;const poss=Math.max(30,Math.min(70,Math.round(home/total*100)));m.stats.home.possession=poss;m.stats.away.possession=100-poss;["home","away"].forEach(side=>{const atk=side==="home"?home:away,opp=side==="home"?away:home,prob=.035+(atk/(total||1))*.055+Math.max(0,atk-opp)*.0005;if(Math.random()<prob){const st=m.stats[side];st.shots++;const on=Math.random()<.38;if(on)st.shotsOnTarget++;st.xg+=on?.16:.05;if(on&&Math.random()<.20){m.score[side]++;m.events.unshift({minute:m.minute,type:"goal",text:"⚽ GOL! "+(side==="home"?m.home:m.away)+" aos "+m.minute+"'."});}else m.events.unshift({minute:m.minute,type:"chance",text:m.minute+"' — chance de "+(side==="home"?m.home:m.away)});}});if(Math.random()<.018){const side=Math.random()<home/total?"home":"away",team=side==="home"?m.home:m.away;m.stats[side].cards++;m.events.unshift({minute:m.minute,type:"yellow",text:"🟨 Cartão para "+team});}if(Math.random()<.005&&this.players(G).length){const p=this.players(G)[Math.floor(Math.random()*this.players(G).length)];p.injured=true;G.state.injuries=G.state.injuries||[];G.state.injuries.push({playerId:p.id,player:p.name,days:3+Math.floor(Math.random()*21)});m.events.unshift({minute:m.minute,type:"injury",text:"🚑 "+p.name+" deixou o campo lesionado."});}if(m.minute===45)m.events.unshift({minute:45,type:"halftime",text:"⏸️ Intervalo."});if(m.minute===60||m.minute===75){const bench=(G.state.bench||[]).map(id=>(G.state.squad||[]).find(p=>p.id===id)).find(p=>p&&!p.injured&&!p.suspended);if(bench){const tired=this.players(G).find(p=>Number(p.condition||80)<45);if(tired){const slot=Object.keys(G.state.lineup||{}).find(k=>G.state.lineup[k]===tired.id);if(slot!==undefined){G.state.lineup[slot]=bench.id;G.state.bench=G.state.bench.filter(id=>id!==bench.id);m.substitutions.push({minute:m.minute,playerOut:tired.id,playerIn:bench.id});m.events.unshift({minute:m.minute,type:"substitution",text:"🔄 "+bench.name+" entrou no lugar de "+tired.name+"."});}}}}this.players(G).forEach(p=>{p.condition=Math.max(25,Number(p.condition||80)-.35);p.form=Math.max(20,Number(p.form||70)-.01);if(m.playerRatings[p.id])m.playerRatings[p.id]=Math.max(4.5,Math.min(9.8,m.playerRatings[p.id]+(Math.random()-.48)*.05));});},
 simulate(G,n){const m=G.state.matchEngine;if(!m?.active)return false;for(let i=0;i<Math.max(1,Number(n)||5)&&m.minute<90;i++){m.minute++;this.minute(G);}if(m.minute>=90)G.finishMatchday();return true;}
};window.MatchCore=M;function wire(){if(!window.Game)return;Game.startMatchday=f=>M.start(Game,f);Game.simulateMatchMinutes=n=>M.simulate(Game,n);}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",wire);else wire();})();